import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const COUNTRIES = [
    { name: 'Saudi Arabia', nameAr: 'السعودية' },
    { name: 'UAE', nameAr: 'الإمارات' },
    { name: 'Kuwait', nameAr: 'الكويت' },
    { name: 'Qatar', nameAr: 'قطر' },
    { name: 'Bahrain', nameAr: 'البحرين' },
    { name: 'Oman', nameAr: 'عمان' },
    { name: 'Yemen', nameAr: 'اليمن' },
    { name: 'Iraq', nameAr: 'العراق' },
    { name: 'Jordan', nameAr: 'الأردن' },
    { name: 'Palestine', nameAr: 'فلسطين' },
    { name: 'Lebanon', nameAr: 'لبنان' },
    { name: 'Syria', nameAr: 'سوريا' },
    { name: 'Turkey', nameAr: 'تركيا' },
    { name: 'Iran', nameAr: 'إيران' },
    { name: 'Afghanistan', nameAr: 'أفغانستان' },
    { name: 'Pakistan', nameAr: 'باكستان' },
    { name: 'India', nameAr: 'الهند' },
    { name: 'Bangladesh', nameAr: 'بنغلاديش' },
    { name: 'Sri Lanka', nameAr: 'سريلانكا' },
    { name: 'Nepal', nameAr: 'نيبال' },
    { name: 'Bhutan', nameAr: 'بوتان' },
    { name: 'Maldives', nameAr: 'المالديف' },
    { name: 'China', nameAr: 'الصين' },
    { name: 'Japan', nameAr: 'اليابان' },
    { name: 'South Korea', nameAr: 'كوريا الجنوبية' },
    { name: 'North Korea', nameAr: 'كوريا الشمالية' },
    { name: 'Taiwan', nameAr: 'تايوان' },
    { name: 'Mongolia', nameAr: 'منغوليا' },
    { name: 'Indonesia', nameAr: 'إندونيسيا' },
    { name: 'Malaysia', nameAr: 'ماليزيا' },
    { name: 'Singapore', nameAr: 'سنغافورة' },
    { name: 'Philippines', nameAr: 'الفلبين' },
    { name: 'Vietnam', nameAr: 'فيتنام' },
    { name: 'Thailand', nameAr: 'تايلاند' },
    { name: 'Myanmar', nameAr: 'ميانمار' },
    { name: 'Cambodia', nameAr: 'كمبوديا' },
    { name: 'Laos', nameAr: 'لاوس' },
    { name: 'Brunei', nameAr: 'بروناي' },
    { name: 'Kazakhstan', nameAr: 'كازاخستان' },
    { name: 'Uzbekistan', nameAr: 'أوزبكستان' },
    { name: 'Turkmenistan', nameAr: 'تركمانستان' },
    { name: 'Kyrgyzstan', nameAr: 'قرغيزستان' },
    { name: 'Tajikistan', nameAr: 'طاجيكستان' },
    { name: 'Azerbaijan', nameAr: 'أذربيجان' },
    { name: 'Armenia', nameAr: 'أرمينيا' },
    { name: 'Georgia', nameAr: 'جورجيا' },
    { name: 'Egypt', nameAr: 'مصر' },
    { name: 'Morocco', nameAr: 'المغرب' },
    { name: 'Algeria', nameAr: 'الجزائر' },
    { name: 'Tunisia', nameAr: 'تونس' },
    { name: 'Libya', nameAr: 'ليبيا' },
    { name: 'Sudan', nameAr: 'السودان' },
    { name: 'Nigeria', nameAr: 'نيجيريا' },
    { name: 'Ghana', nameAr: 'غانا' },
    { name: 'Senegal', nameAr: 'السنغال' },
    { name: 'Mali', nameAr: 'مالي' },
    { name: 'Niger', nameAr: 'النيجر' },
    { name: 'Côte d\'Ivoire', nameAr: 'ساحل العاج' },
    { name: 'Burkina Faso', nameAr: 'بوركينا فاسو' },
    { name: 'Guinea', nameAr: 'غينيا' },
    { name: 'Benin', nameAr: 'بنين' },
    { name: 'Togo', nameAr: 'توجو' },
    { name: 'Liberia', nameAr: 'ليبيريا' },
    { name: 'Sierra Leone', nameAr: 'سيراليون' },
    { name: 'Gambia', nameAr: 'غامبيا' },
    { name: 'Guinea-Bissau', nameAr: 'غينيا بيساو' },
    { name: 'Mauritania', nameAr: 'موريتانيا' },
    { name: 'Cape Verde', nameAr: 'الرأس الأخضر' },
    { name: 'Ethiopia', nameAr: 'إثيوبيا' },
    { name: 'Kenya', nameAr: 'كينيا' },
    { name: 'Tanzania', nameAr: 'تنزانيا' },
    { name: 'Uganda', nameAr: 'أوغندا' },
    { name: 'Somalia', nameAr: 'الصومال' },
    { name: 'Rwanda', nameAr: 'رواندا' },
    { name: 'Burundi', nameAr: 'بوروندي' },
    { name: 'Djibouti', nameAr: 'جيبوتي' },
    { name: 'Eritrea', nameAr: 'إريتريا' },
    { name: 'Madagascar', nameAr: 'مدغشقر' },
    { name: 'Seychelles', nameAr: 'سيشل' },
    { name: 'Comoros', nameAr: 'جزر القمر' },
    { name: 'Mauritius', nameAr: 'موريشيوس' },
    { name: 'DR Congo', nameAr: 'الكونغو الديمقراطية' },
    { name: 'Angola', nameAr: 'أنغولا' },
    { name: 'Cameroon', nameAr: 'الكاميرون' },
    { name: 'Chad', nameAr: 'تشاد' },
    { name: 'Congo', nameAr: 'الكونغو' },
    { name: 'Central African Republic', nameAr: 'إفريقيا الوسطى' },
    { name: 'Gabon', nameAr: 'الغابون' },
    { name: 'Equatorial Guinea', nameAr: 'غينيا الاستوائية' },
    { name: 'Sao Tome and Principe', nameAr: 'ساو تومي وبرينسيب' },
    { name: 'South Africa', nameAr: 'جنوب إفريقيا' },
    { name: 'Zimbabwe', nameAr: 'زيمبابوي' },
    { name: 'Zambia', nameAr: 'زامبيا' },
    { name: 'Mozambique', nameAr: 'موزمبيق' },
    { name: 'Malawi', nameAr: 'مالاوي' },
    { name: 'Namibia', nameAr: 'ناميبيا' },
    { name: 'Botswana', nameAr: 'بوتسوانا' },
    { name: 'Lesotho', nameAr: 'ليسوتو' },
    { name: 'Eswatini', nameAr: 'إسواتيني' },
    { name: 'UK', nameAr: 'بريطانيا' },
    { name: 'Ireland', nameAr: 'أيرلندا' },
    { name: 'France', nameAr: 'فرنسا' },
    { name: 'Germany', nameAr: 'ألمانيا' },
    { name: 'Netherlands', nameAr: 'هولندا' },
    { name: 'Belgium', nameAr: 'بلجيكا' },
    { name: 'Switzerland', nameAr: 'سويسرا' },
    { name: 'Austria', nameAr: 'النمسا' },
    { name: 'Sweden', nameAr: 'السويد' },
    { name: 'Norway', nameAr: 'النرويج' },
    { name: 'Denmark', nameAr: 'الدنمارك' },
    { name: 'Finland', nameAr: 'فنلندا' },
    { name: 'Iceland', nameAr: 'أيسلندا' },
    { name: 'Italy', nameAr: 'إيطاليا' },
    { name: 'Spain', nameAr: 'إسبانيا' },
    { name: 'Portugal', nameAr: 'البرتغال' },
    { name: 'Greece', nameAr: 'اليونان' },
    { name: 'Russia', nameAr: 'روسيا' },
    { name: 'Ukraine', nameAr: 'أوكرانيا' },
    { name: 'Poland', nameAr: 'بولندا' },
    { name: 'Romania', nameAr: 'رومانيا' },
    { name: 'Czechia', nameAr: 'التشيك' },
    { name: 'Hungary', nameAr: 'المجر' },
    { name: 'Serbia', nameAr: 'صربيا' },
    { name: 'Bulgaria', nameAr: 'بلغاريا' },
    { name: 'Croatia', nameAr: 'كرواتيا' },
    { name: 'Bosnia', nameAr: 'البوسنة' },
    { name: 'Albania', nameAr: 'ألبانيا' },
    { name: 'USA (NY)', nameAr: 'أمريكا (نيويورك)' },
    { name: 'USA (LA)', nameAr: 'أمريكا (لوس أنجلوس)' },
    { name: 'USA (Chicago)', nameAr: 'أمريكا (شيكاغو)' },
    { name: 'Canada (Toronto)', nameAr: 'كندا (تورونتو)' },
    { name: 'Canada (Vancouver)', nameAr: 'كندا (فانكوفر)' },
    { name: 'Mexico', nameAr: 'المكسيك' },
    { name: 'Cuba', nameAr: 'كوبا' },
    { name: 'Jamaica', nameAr: 'جامايكا' },
    { name: 'Panama', nameAr: 'بنما' },
    { name: 'Costa Rica', nameAr: 'كوستاريكا' },
    { name: 'Dominican Republic', nameAr: 'الدومينيكان' },
    { name: 'Haiti', nameAr: 'هايتي' },
    { name: 'Brazil (Rio)', nameAr: 'البرازيل (ريو)' },
    { name: 'Brazil (Manaus)', nameAr: 'البرازيل (ماناوس)' },
    { name: 'Argentina', nameAr: 'الأرجنتين' },
    { name: 'Chile', nameAr: 'تشيلي' },
    { name: 'Colombia', nameAr: 'كولومبيا' },
    { name: 'Peru', nameAr: 'بيرو' },
    { name: 'Venezuela', nameAr: 'فنزويلا' },
    { name: 'Ecuador', nameAr: 'الإكوادور' },
    { name: 'Bolivia', nameAr: 'بوليڤيا' },
    { name: 'Paraguay', nameAr: 'باراغواي' },
    { name: 'Uruguay', nameAr: 'أوروغواي' },
    { name: 'Australia (Sydney)', nameAr: 'أستراليا (سيدني)' },
    { name: 'Australia (Perth)', nameAr: 'أستراليا (بيرث)' },
    { name: 'New Zealand', nameAr: 'نيوزيلندا' },
    { name: 'Fiji', nameAr: 'فيجي' },
    { name: 'Papua New Guinea', nameAr: 'بابوا غينيا الجديدة' },
    { name: 'Samoa', nameAr: 'ساموا' }
];

const EXISTING = {
    "Saudi Arabia": {
        id: "Saudi Arabia",
        cities: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
        citiesAr: ["الرياض", "جدة", "مكة المكرمة", "المدينة المنورة", "الدمام"],
        governance: "Absolute Monarchy",
        governanceAr: "ملكية مطلقة",
        ruler: "King Salman bin Abdulaziz",
        rulerAr: "الملك سلمان بن عبد العزيز",
        muslimPopulation: "approx. 32 million (93%)",
        muslimPopulationAr: "حوالي 32 مليون (93%)",
        muslimSafetyPercentage: 100,
        location: "Middle East, Western Asia",
        locationAr: "الشرق الأوسط، غرب آسيا",
        features: ["Two Holy Mosques", "Oil Resources", "Vision 2030", "Ancient Nabataean Sites"],
        featuresAr: ["الحرمين الشريفين", "الموارد النفطية", "رؤية 2030", "المواقع النبطية القديمة"]
    },
    "Morocco": {
        id: "Morocco",
        cities: ["Rabat", "Casablanca", "Marrakesh", "Fes", "Tangier"],
        citiesAr: ["الرباط", "الدار البيضاء", "مراكش", "فاس", "طنجة"],
        governance: "Constitutional Monarchy",
        governanceAr: "ملكية دستورية",
        ruler: "King Mohammed VI",
        rulerAr: "الملك محمد السادس",
        muslimPopulation: "approx. 37 million (99%)",
        muslimPopulationAr: "حوالي 37 مليون (99%)",
        muslimSafetyPercentage: 100,
        location: "North Africa, Maghreb",
        locationAr: "شمال أفريقيا، المغرب العربي",
        features: ["Andalusian Architecture", "Atlas Mountains", "Sahara Desert", "Traditional Tea & Cuisine"],
        featuresAr: ["العمارة الأندلسية", "جبال الأطلس", "الصحراء الكبرى", "الشاي والمطبخ المغربي"]
    },
    "UAE": {
        id: "UAE",
        cities: ["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Al Ain"],
        citiesAr: ["أبوظبي", "دبي", "الشارقة", "عجمان", "العين"],
        governance: "Federal Elective Monarchy",
        governanceAr: "ملكية اتحادية وراثية",
        ruler: "Sheikh Mohamed bin Zayed Al Nanhyan",
        rulerAr: "الشيخ محمد بن زايد آل نهيان",
        muslimPopulation: "approx. 7.5 million (76%)",
        muslimPopulationAr: "حوالي 7.5 مليون (76%)",
        muslimSafetyPercentage: 100,
        location: "Middle East, Arabian Peninsula",
        locationAr: "الشرق الأوسط، الجزيرة العربية",
        features: ["Burj Khalifa", "Global Trade Hub", "Space Program", "Palm Jumeirah"],
        featuresAr: ["برج خليفة", "مركز تجارة عالمي", "برنامج الفضاء", "نخلة الجميرة"]
    },
    "Egypt": {
        id: "Egypt",
        cities: ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said"],
        citiesAr: ["القاهرة", "الإسكندرية", "الجيزة", "شبرا الخيمة", "بورسعيد"],
        governance: "Republic",
        governanceAr: "جمهورية",
        ruler: "Abdel Fattah el-Sisi",
        rulerAr: "عبد الفتاح السيسي",
        muslimPopulation: "approx. 95 million (90%)",
        muslimPopulationAr: "حوالي 95 مليون (90%)",
        muslimSafetyPercentage: 98,
        location: "North Africa",
        locationAr: "شمال أفريقيا",
        features: ["Pyramids of Giza", "Nile River", "Al-Azhar University", "Ancient History"],
        featuresAr: ["أهرامات الجيزة", "نهر النيل", "جامعة الأزهر", "التاريخ والآثار القديمة"]
    },
    "Turkey": {
        id: "Turkey",
        cities: ["Ankara", "Istanbul", "Izmir", "Bursa", "Antalya"],
        citiesAr: ["أنقرة", "إسطنبول", "إزمير", "بورصة", "أنطاليا"],
        governance: "Presidential Republic",
        governanceAr: "جمهورية رئاسية",
        ruler: "Recep Tayyip Erdoğan",
        rulerAr: "رجب طيب أردوغان",
        muslimPopulation: "approx. 83 million (99%)",
        muslimPopulationAr: "حوالي 83 مليون (99%)",
        muslimSafetyPercentage: 99,
        location: "Western Asia & Southeast Europe",
        locationAr: "غرب آسيا وجنوب شرق أوروبا",
        features: ["Hagia Sophia", "Bridge between East & West", "Turkish Textile Industry", "Diverse Landscapes"],
        featuresAr: ["آيا صوفيا", "جسر بين الشرق والغرب", "صناعة المنسوجات", "تنوع التضاريس"]
    },
    "Palestine": {
        id: "Palestine",
        cities: ["Jerusalem", "Gaza City", "Hebron", "Nablus", "Ramallah"],
        citiesAr: ["القدس الشريف", "غزة", "الخليل", "نابلس", "رام الله"],
        governance: "Semi-presidential Republic",
        governanceAr: "جمهورية شبه رئاسية",
        ruler: "Mahmoud Abbas",
        rulerAr: "محمود عباس",
        muslimPopulation: "approx. 5 million (93%)",
        muslimPopulationAr: "حوالي 5 مليون (93%)",
        muslimSafetyPercentage: 20,
        location: "Middle East, Levant",
        locationAr: "الشرق الأوسط، بلاد الشام",
        features: ["Al-Aqsa Mosque", "Church of the Holy Sepulchre", "Old City of Jerusalem", "Olive Groves"],
        featuresAr: ["المسجد الأقصى", "كنيسة القيامة", "البلدة القديمة بالقدس", "بساتين الزيتون"]
    },
    "Algeria": {
        id: "Algeria",
        cities: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
        citiesAr: ["الجزائر العاصمة", "وهران", "قسنطينة", "عنابة", "البليدة"],
        governance: "Semi-presidential Republic",
        governanceAr: "جمهورية شبه رئاسية",
        ruler: "Abdelmadjid Tebboune",
        rulerAr: "عبد المجيد تبون",
        muslimPopulation: "approx. 44 million (99%)",
        muslimPopulationAr: "حوالي 44 مليون (99%)",
        muslimSafetyPercentage: 100,
        location: "North Africa, Maghreb",
        locationAr: "شمال أفريقيا، المغرب العربي",
        features: ["Largest country in Africa", "Saharan Heritage", "Mediterranean Coastline", "Rich History"],
        featuresAr: ["أكبر دولة في أفريقيا", "التراث الصحراوي", "الساحل المتوسطي", "تاريخ نضالي عريق"]
    },
    "Indonesia": {
        id: "Indonesia",
        cities: ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang"],
        citiesAr: ["جاكرتا", "سورابايا", "باندونج", "ميدان", "سمارانج"],
        governance: "Republic",
        governanceAr: "جمهورية",
        ruler: "Prabowo Subianto",
        rulerAr: "برابوو سوبيانتو",
        muslimPopulation: "approx. 231 million (87%)",
        muslimPopulationAr: "حوالي 231 مليون (87%)",
        muslimSafetyPercentage: 97,
        location: "Southeast Asia",
        locationAr: "جنوب شرق آسيا",
        features: ["Largest Muslim-majority country", "Archipelago (17k+ islands)", "Tropical Biodiversity", "Borobudur Temple"],
        featuresAr: ["أكبر بلد إسلامي ديموغرافياً", "أرخبيل شاسع", "تنوع بيولوجي استوائي", "معبد بوروبودور التاريخي"]
    },
    "Malaysia": {
        id: "Malaysia",
        cities: ["Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Johor Bahru"],
        citiesAr: ["كوالالمبور", "جورج تاون", "إيبوه", "شاه علم", "جوهر بهرو"],
        governance: "Federal Constitutional Monarchy",
        governanceAr: "ملكية دستورية اتحادية",
        ruler: "Sultan Ibrahim ibni Sultan Iskandar",
        rulerAr: "السلطان إبراهيم بن السلطان إسكندر",
        muslimPopulation: "approx. 20 million (63%)",
        muslimPopulationAr: "حوالي 20 مليون (63%)",
        muslimSafetyPercentage: 100,
        location: "Southeast Asia",
        locationAr: "جنوب شرق آسيا",
        features: ["Petronas Twin Towers", "Multiculturalism", "Tropical Rainforests", "Advanced Tech Sector"],
        featuresAr: ["برجا بتروناس التوأم", "التنوع الثقافي", "الغابات الاستوائية", "قطاع تقني متقدم"]
    },
    "Kuwait": {
        id: "Kuwait",
        cities: ["Kuwait City", "Al Ahmadi", "Hawalli", "Salmiya", "Sabah Al Salem"],
        citiesAr: ["مدينة الكويت", "الأحمدي", "حولي", "السالمية", "صباح السالم"],
        governance: "Unitary Semi-constitutional Monarchy",
        governanceAr: "ملكية دستورية",
        ruler: "Sheikh Mishal Al-Ahmad Al-Jaber Al-Sabah",
        rulerAr: "الشيخ مشعل الأحمد الجابر الصباح",
        muslimPopulation: "approx. 3.5 million (74%)",
        muslimPopulationAr: "حوالي 3.5 مليون (74%)",
        muslimSafetyPercentage: 100,
        location: "Middle East, Arabian Peninsula",
        locationAr: "الشرق الأوسط، الجزيرة العربية",
        features: ["Kuwait Towers", "Old Souq Sharq", "Traditional Maritime Heritage", "Rich Oil Industry"],
        featuresAr: ["أبراج الكويت", "سوق شرق القديم", "التراث البحري العريق", "صناعة النفط المزدهرة"]
    },
    "Qatar": {
        id: "Qatar",
        cities: ["Doha", "Al Wakrah", "Al Khor", "Al Rayyan", "Madinat ash Shamal"],
        citiesAr: ["الدوحة", "الوكرة", "الخور", "الريان", "مدينة الشمال"],
        governance: "Semi-constitutional Monarchy",
        governanceAr: "ملكية شبه دستورية",
        ruler: "Sheikh Tamim bin Hamad Al Thani",
        rulerAr: "الشيخ تميم بن حمد آل ثاني",
        muslimPopulation: "approx. 2.1 million (67%)",
        muslimPopulationAr: "حوالي 2.1 مليون (67%)",
        muslimSafetyPercentage: 100,
        location: "Middle East, Arabian Peninsula",
        locationAr: "الشرق الأوسط، الجزيرة العربية",
        features: ["2022 FIFA World Cup Host", "Modern Skyline", "Museum of Islamic Art", "High GDP per Capita"],
        featuresAr: ["استضافة مونديال 2022", "أفق الدوحة الحديث", "متحف الفن الإسلامي", "أعلى دخل للفرد"]
    },
    "Jordan": {
        id: "Jordan",
        cities: ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba"],
        citiesAr: ["عمان", "الزرقاء", "إربد", "العقبة", "مادبا"],
        governance: "Constitutional Monarchy",
        governanceAr: "ملكية دستورية",
        ruler: "King Abdullah II",
        rulerAr: "الملك عبد الله الثاني",
        muslimPopulation: "approx. 10 million (97%)",
        muslimPopulationAr: "حوالي 10 مليون (97%)",
        muslimSafetyPercentage: 100,
        location: "Middle East, Levant",
        locationAr: "الشرق الأوسط، بلاد الشام",
        features: ["Petra (World Wonder)", "Wadi Rum", "Dead Sea", "Roman Ruins"],
        featuresAr: ["مدينة البتراء (من العجائب)", "وادي رم", "البحر الميت", "الآثار الرومانية"]
    },
    "USA (NY)": {
        id: "USA (NY)",
        cities: ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse"],
        citiesAr: ["مدينة نيويورك", "بافالو", "روتشستر", "يونكيرس", "سيراكيوز"],
        governance: "Federal Presidential Republic",
        governanceAr: "جمهورية رئاسية اتحادية",
        ruler: "Executive Leadership",
        rulerAr: "القيادة التنفيذية",
        muslimPopulation: "approx. 1 million in NY",
        muslimPopulationAr: "حوالي مليون نسمة في نيويورك",
        muslimSafetyPercentage: 95,
        location: "North America, East Coast",
        locationAr: "أمريكا الشمالية، الساحل الشرقي",
        features: ["Statue of Liberty", "Financial District (Wall St)", "Times Square", "Cultural Diversity"],
        featuresAr: ["تمثال الحرية", "الحي المالي (وول ستريت)", "تايمز سكوير", "التنوع الثقافي"]
    },
    "UK": {
        id: "UK",
        cities: ["London", "Manchester", "Birmingham", "Leeds", "Glasgow"],
        citiesAr: ["لندن", "مانشستر", "برمنغهام", "ليدز", "غلاسكو"],
        governance: "Parliamentary Monarchy",
        governanceAr: "ملكية برلمانية",
        ruler: "King Charles III",
        rulerAr: "الملك تشارلز الثالث",
        muslimPopulation: "approx. 4 million (6%)",
        muslimPopulationAr: "حوالي 4 مليون (6%)",
        muslimSafetyPercentage: 94,
        location: "Western Europe, Island",
        locationAr: "أوروبا الغربية، جزيرة",
        features: ["Big Ben", "London Eye", "Premier League", "Historical Landmarks"],
        featuresAr: ["ساعة بيغ بن", "لندن آي", "الدوري الإنجليزي الممتاز", "المعالم التاريخية"]
    },
    "France": {
        id: "France",
        cities: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice"],
        citiesAr: ["باريس", "ليون", "مارسيليا", "تولوز", "نيس"],
        governance: "Semi-presidential Republic",
        governanceAr: "جمهورية شبه رئاسية",
        ruler: "Emmanuel Macron",
        rulerAr: "إيمانويل ماكرون",
        muslimPopulation: "approx. 5.7 million (9%)",
        muslimPopulationAr: "حوالي 5.7 مليون (9%)",
        muslimSafetyPercentage: 90,
        location: "Western Europe",
        locationAr: "أوروبا الغربية",
        features: ["Eiffel Tower", "Louvre Museum", "World-class Gastronomy", "Fashion Capitals"],
        featuresAr: ["برج إيفل", "متحف اللوفر", "المطبخ العالمي", "عواصم الموضة"]
    },
    "Iran": {
        id: "Iran",
        cities: ["Tehran", "Mashhad", "Isfahan", "Tabriz", "Shiraz"],
        citiesAr: ["طهران", "مشهد", "أصفهان", "تبريز", "شيراز"],
        governance: "Islamic Republic",
        governanceAr: "جمهورية إسلامية",
        ruler: "Ali Khamenei",
        rulerAr: "علي خامنئي",
        muslimPopulation: "approx. 88.5 million (99%)",
        muslimPopulationAr: "حوالي 88.5 مليون (99%)",
        muslimSafetyPercentage: 100,
        location: "Western Asia",
        locationAr: "غرب آسيا",
        features: ["Ancient Persian History", "Carpet Weaving", "Saffron Production", "Poetry"],
        featuresAr: ["التاريخ الفارسي العريق", "صناعة السجاد", "إنتاج الزعفران", "الشعر والأدب"]
    }
};

const outputDir = path.join(__dirname, 'src', 'data', 'countries');

if (fs.existsSync(outputDir)) {
    fs.rmSync(outputDir, { recursive: true, force: true });
}
fs.mkdirSync(outputDir, { recursive: true });

let exportsList = [];
let reexportKeys = [];

for (const country of COUNTRIES) {
    const key = country.name;
    const folderName = key.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const countryDir = path.join(outputDir, folderName);
    const varName = folderName.replace(/-([a-z])/g, (g) => g[1].toUpperCase());

    fs.mkdirSync(countryDir, { recursive: true });

    let detail = EXISTING[key];
    if (!detail) {
        detail = {
            id: key,
            city: "",
            cityAr: "",
            governance: "---",
            governanceAr: "---",
            ruler: "---",
            rulerAr: "---",
            muslimPopulation: "---",
            muslimPopulationAr: "---",
            muslimSafetyPercentage: 0,
            location: "---",
            locationAr: "---",
            features: ["No Data"],
            featuresAr: ["لا توجد بيانات"],
            cities: [],
            citiesAr: []
        };
    }

    const tsContent = `import { CountryDetail } from '../worldTimesData';\n\nexport const ${varName}: CountryDetail = ${JSON.stringify(detail, null, 4)};\n`;

    fs.writeFileSync(path.join(countryDir, 'index.ts'), tsContent, 'utf-8');

    exportsList.push(`import { ${varName} } from './${folderName}';`);
    reexportKeys.push(`    "${key}": ${varName}`);
}

const indexContent = `${exportsList.join('\n')}\n\nexport const COUNTRY_DETAILS_REFACTORED = {\n${reexportKeys.join(',\n')}\n};\n`;
fs.writeFileSync(path.join(outputDir, 'index.ts'), indexContent, 'utf-8');

console.log('Extraction complete!');
